version: '3.7'
services:
  mssql:
    container_name: sql-server-api-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1@"
      ACCEPT_EULA: "Y"
      